---
default:
    # Directory to store outputs
    output_folder: "output"
    output_folder_hca: "hca"
    output_folder_pca: "pca"

    # Input table locations
    spectral_table: "data/Table.dat"
    mass_table: "data/Variables_m.dat"
    time_table: "data/Variables_t.dat"
    sample_names: "data/Analyses.dat"

    # Do you need sample name pattern matching?
    # Accepts: "TRUE" and "FAlSE"
    pattern_needed: TRUE
    # Pattern for sample name matching
    # Accepts regex patterns
    row_name_pattern: "[AB][0-9]{3}"

    # Generate tree based on number of members or variance of cluster
    # Accepts: "num" or "var"
    numOrVar: "var"

    # The cut-off value for either setting from above
    # Accepts: any positive rational number
    N_numOrVar: 20

    # The number of maximum points to display on a loadings plot
    # use this if script gets killed because of OOM (Out of Memory)
    max_points_loadings: 5000

    # Save image after computing overall PCA, HCA
    # Accepts: True, False, and all these https://yaml.org/type/bool.html
    save_image: TRUE
... 
