---
default:
    # Location of accessory_functions.R (do not change if using docker)
    # if using host system, change to wherever both hcapca.R and 
    # accessory_functions.R are located
    # input_folder_accessory_script: "/script"
    input_folder_accessory_script: "~/programming/hcapca/src"

    # Directory to store outputs
    output_folder: "output"

    # Will be created inside directory "output_folder"
    output_folder_hca: "hca"
    output_folder_pca: "pca"

    # Input table locations
    spectral_table: "data/Table.dat"
    mass_table: "data/Variables_m.dat"
    time_table: "data/Variables_t.dat"
    sample_names: "data/Analyses.dat"

    # Run Shiny App to see results?
    # Accepts: TRUE/FALSE
    run_shiny_app: TRUE

    # Shiny App Directory (will be /script for docker)
    # shiny_app_folder: "/script"
    shiny_app_folder: "~/programming/hcapca/src"

    # Pattern for sample name matching; if you do not need pattern matching,
    # please enter ".*" as the pattern.
    # Accepts: regex patterns
    row_name_pattern: ".*"


    # Generate tree based on number of members or variance of cluster
    # Accepts: "num" or "var"
    numOrVar: "var"

    # The cut-off value for either setting from above
    # Accepts: any positive rational number
    N_numOrVar: 20

    # The number of maximum points to display on a loadings plot
    # use this if script gets killed because of OOM (Out of Memory)
    max_points_loadings: 5000

    # Save image after computing overall PCA, HCA
    # Accepts: True, False, and all these https://yaml.org/type/bool.html
    save_image: TRUE
... 
