#!docker run --rm -it biocontainers/clustal-omega:v1.2.1_cv5
!echo "Pre-alignment"
!ls example/data/processed
!docker run \
    --rm \
    -v $(pwd)/example/data:/output \
    biocontainers/clustal-omega:v1.2.1_cv5 \
        clustalo -i /output/processed/orgs_yenB.faa \
        --force \
        --auto -o /output/processed/orgs_yenB.aln
!echo "Post-alignment"        
!ls example/data/processed
